log:
  access_file:
  error_file:

db:
  dialect:
  path:
  migrations:

metric:
  address:
  port:
  cpu_weight:
  memory_weight:
  network_weight:

port_assignment:
  start_port:
  end_port:

worker_server:
  address:
  port:
