// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proxy/xray/proto/inbound/inbound.proto

package inboun

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TypedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypedMessage) Reset() {
	*x = TypedMessage{}
	mi := &file_proxy_xray_proto_inbound_inbound_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypedMessage) ProtoMessage() {}

func (x *TypedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_xray_proto_inbound_inbound_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypedMessage.ProtoReflect.Descriptor instead.
func (*TypedMessage) Descriptor() ([]byte, []int) {
	return file_proxy_xray_proto_inbound_inbound_proto_rawDescGZIP(), []int{0}
}

func (x *TypedMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TypedMessage) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type InboundHandlerConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Tag              string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	ReceiverSettings *TypedMessage          `protobuf:"bytes,2,opt,name=receiver_settings,json=receiverSettings,proto3" json:"receiver_settings,omitempty"`
	ProxySettings    *TypedMessage          `protobuf:"bytes,3,opt,name=proxy_settings,json=proxySettings,proto3" json:"proxy_settings,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InboundHandlerConfig) Reset() {
	*x = InboundHandlerConfig{}
	mi := &file_proxy_xray_proto_inbound_inbound_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboundHandlerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundHandlerConfig) ProtoMessage() {}

func (x *InboundHandlerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_xray_proto_inbound_inbound_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundHandlerConfig.ProtoReflect.Descriptor instead.
func (*InboundHandlerConfig) Descriptor() ([]byte, []int) {
	return file_proxy_xray_proto_inbound_inbound_proto_rawDescGZIP(), []int{1}
}

func (x *InboundHandlerConfig) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *InboundHandlerConfig) GetReceiverSettings() *TypedMessage {
	if x != nil {
		return x.ReceiverSettings
	}
	return nil
}

func (x *InboundHandlerConfig) GetProxySettings() *TypedMessage {
	if x != nil {
		return x.ProxySettings
	}
	return nil
}

type AddInboundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inbound       *InboundHandlerConfig  `protobuf:"bytes,1,opt,name=inbound,proto3" json:"inbound,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddInboundRequest) Reset() {
	*x = AddInboundRequest{}
	mi := &file_proxy_xray_proto_inbound_inbound_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddInboundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddInboundRequest) ProtoMessage() {}

func (x *AddInboundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_xray_proto_inbound_inbound_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddInboundRequest.ProtoReflect.Descriptor instead.
func (*AddInboundRequest) Descriptor() ([]byte, []int) {
	return file_proxy_xray_proto_inbound_inbound_proto_rawDescGZIP(), []int{2}
}

func (x *AddInboundRequest) GetInbound() *InboundHandlerConfig {
	if x != nil {
		return x.Inbound
	}
	return nil
}

type AddInboundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddInboundResponse) Reset() {
	*x = AddInboundResponse{}
	mi := &file_proxy_xray_proto_inbound_inbound_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddInboundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddInboundResponse) ProtoMessage() {}

func (x *AddInboundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_xray_proto_inbound_inbound_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddInboundResponse.ProtoReflect.Descriptor instead.
func (*AddInboundResponse) Descriptor() ([]byte, []int) {
	return file_proxy_xray_proto_inbound_inbound_proto_rawDescGZIP(), []int{3}
}

var File_proxy_xray_proto_inbound_inbound_proto protoreflect.FileDescriptor

const file_proxy_xray_proto_inbound_inbound_proto_rawDesc = "" +
	"\n" +
	"&proxy/xray/proto/inbound/inbound.proto\x12\ainbound\"8\n" +
	"\fTypedMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\xaa\x01\n" +
	"\x14InboundHandlerConfig\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12B\n" +
	"\x11receiver_settings\x18\x02 \x01(\v2\x15.inbound.TypedMessageR\x10receiverSettings\x12<\n" +
	"\x0eproxy_settings\x18\x03 \x01(\v2\x15.inbound.TypedMessageR\rproxySettings\"L\n" +
	"\x11AddInboundRequest\x127\n" +
	"\ainbound\x18\x01 \x01(\v2\x1d.inbound.InboundHandlerConfigR\ainbound\"\x14\n" +
	"\x12AddInboundResponse2Y\n" +
	"\x0eHandlerService\x12G\n" +
	"\n" +
	"AddInbound\x12\x1a.inbound.AddInboundRequest\x1a\x1b.inbound.AddInboundResponse\"\x00B\x1eZ\x1cmomo/proxy/xray/proto/inbounb\x06proto3"

var (
	file_proxy_xray_proto_inbound_inbound_proto_rawDescOnce sync.Once
	file_proxy_xray_proto_inbound_inbound_proto_rawDescData []byte
)

func file_proxy_xray_proto_inbound_inbound_proto_rawDescGZIP() []byte {
	file_proxy_xray_proto_inbound_inbound_proto_rawDescOnce.Do(func() {
		file_proxy_xray_proto_inbound_inbound_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_xray_proto_inbound_inbound_proto_rawDesc), len(file_proxy_xray_proto_inbound_inbound_proto_rawDesc)))
	})
	return file_proxy_xray_proto_inbound_inbound_proto_rawDescData
}

var file_proxy_xray_proto_inbound_inbound_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proxy_xray_proto_inbound_inbound_proto_goTypes = []any{
	(*TypedMessage)(nil),         // 0: inbound.TypedMessage
	(*InboundHandlerConfig)(nil), // 1: inbound.InboundHandlerConfig
	(*AddInboundRequest)(nil),    // 2: inbound.AddInboundRequest
	(*AddInboundResponse)(nil),   // 3: inbound.AddInboundResponse
}
var file_proxy_xray_proto_inbound_inbound_proto_depIdxs = []int32{
	0, // 0: inbound.InboundHandlerConfig.receiver_settings:type_name -> inbound.TypedMessage
	0, // 1: inbound.InboundHandlerConfig.proxy_settings:type_name -> inbound.TypedMessage
	1, // 2: inbound.AddInboundRequest.inbound:type_name -> inbound.InboundHandlerConfig
	2, // 3: inbound.HandlerService.AddInbound:input_type -> inbound.AddInboundRequest
	3, // 4: inbound.HandlerService.AddInbound:output_type -> inbound.AddInboundResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proxy_xray_proto_inbound_inbound_proto_init() }
func file_proxy_xray_proto_inbound_inbound_proto_init() {
	if File_proxy_xray_proto_inbound_inbound_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_xray_proto_inbound_inbound_proto_rawDesc), len(file_proxy_xray_proto_inbound_inbound_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proxy_xray_proto_inbound_inbound_proto_goTypes,
		DependencyIndexes: file_proxy_xray_proto_inbound_inbound_proto_depIdxs,
		MessageInfos:      file_proxy_xray_proto_inbound_inbound_proto_msgTypes,
	}.Build()
	File_proxy_xray_proto_inbound_inbound_proto = out.File
	file_proxy_xray_proto_inbound_inbound_proto_goTypes = nil
	file_proxy_xray_proto_inbound_inbound_proto_depIdxs = nil
}
