// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: contract/protobuf/port/port.proto

package port

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PortAssignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          string                 `protobuf:"bytes,1,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortAssignResponse) Reset() {
	*x = PortAssignResponse{}
	mi := &file_contract_protobuf_port_port_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortAssignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortAssignResponse) ProtoMessage() {}

func (x *PortAssignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_protobuf_port_port_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortAssignResponse.ProtoReflect.Descriptor instead.
func (*PortAssignResponse) Descriptor() ([]byte, []int) {
	return file_contract_protobuf_port_port_proto_rawDescGZIP(), []int{0}
}

func (x *PortAssignResponse) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

type PortAssignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortAssignRequest) Reset() {
	*x = PortAssignRequest{}
	mi := &file_contract_protobuf_port_port_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortAssignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortAssignRequest) ProtoMessage() {}

func (x *PortAssignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_protobuf_port_port_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortAssignRequest.ProtoReflect.Descriptor instead.
func (*PortAssignRequest) Descriptor() ([]byte, []int) {
	return file_contract_protobuf_port_port_proto_rawDescGZIP(), []int{1}
}

var File_contract_protobuf_port_port_proto protoreflect.FileDescriptor

const file_contract_protobuf_port_port_proto_rawDesc = "" +
	"\n" +
	"!contract/protobuf/port/port.proto\x12\x04port\"(\n" +
	"\x12PortAssignResponse\x12\x12\n" +
	"\x04port\x18\x01 \x01(\tR\x04port\"\x13\n" +
	"\x11PortAssignRequest2M\n" +
	"\x04Port\x12E\n" +
	"\x10GetAvailablePort\x12\x17.port.PortAssignRequest\x1a\x18.port.PortAssignResponseB\x16Z\x14contract/gogrpc/portb\x06proto3"

var (
	file_contract_protobuf_port_port_proto_rawDescOnce sync.Once
	file_contract_protobuf_port_port_proto_rawDescData []byte
)

func file_contract_protobuf_port_port_proto_rawDescGZIP() []byte {
	file_contract_protobuf_port_port_proto_rawDescOnce.Do(func() {
		file_contract_protobuf_port_port_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contract_protobuf_port_port_proto_rawDesc), len(file_contract_protobuf_port_port_proto_rawDesc)))
	})
	return file_contract_protobuf_port_port_proto_rawDescData
}

var file_contract_protobuf_port_port_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_contract_protobuf_port_port_proto_goTypes = []any{
	(*PortAssignResponse)(nil), // 0: port.PortAssignResponse
	(*PortAssignRequest)(nil),  // 1: port.PortAssignRequest
}
var file_contract_protobuf_port_port_proto_depIdxs = []int32{
	1, // 0: port.Port.GetAvailablePort:input_type -> port.PortAssignRequest
	0, // 1: port.Port.GetAvailablePort:output_type -> port.PortAssignResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_contract_protobuf_port_port_proto_init() }
func file_contract_protobuf_port_port_proto_init() {
	if File_contract_protobuf_port_port_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contract_protobuf_port_port_proto_rawDesc), len(file_contract_protobuf_port_port_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contract_protobuf_port_port_proto_goTypes,
		DependencyIndexes: file_contract_protobuf_port_port_proto_depIdxs,
		MessageInfos:      file_contract_protobuf_port_port_proto_msgTypes,
	}.Build()
	File_contract_protobuf_port_port_proto = out.File
	file_contract_protobuf_port_port_proto_goTypes = nil
	file_contract_protobuf_port_port_proto_depIdxs = nil
}
