// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: contract/protobuf/port/port.proto

package port

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PortAssignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ports         []string               `protobuf:"bytes,1,rep,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortAssignResponse) Reset() {
	*x = PortAssignResponse{}
	mi := &file_contract_protobuf_port_port_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortAssignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortAssignResponse) ProtoMessage() {}

func (x *PortAssignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_protobuf_port_port_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortAssignResponse.ProtoReflect.Descriptor instead.
func (*PortAssignResponse) Descriptor() ([]byte, []int) {
	return file_contract_protobuf_port_port_proto_rawDescGZIP(), []int{0}
}

func (x *PortAssignResponse) GetPorts() []string {
	if x != nil {
		return x.Ports
	}
	return nil
}

type PortAssignRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PortsUsed           []string               `protobuf:"bytes,1,rep,name=portsUsed,proto3" json:"portsUsed,omitempty"`
	RequestNumberOfPort uint32                 `protobuf:"varint,2,opt,name=requestNumberOfPort,proto3" json:"requestNumberOfPort,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PortAssignRequest) Reset() {
	*x = PortAssignRequest{}
	mi := &file_contract_protobuf_port_port_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortAssignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortAssignRequest) ProtoMessage() {}

func (x *PortAssignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_protobuf_port_port_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortAssignRequest.ProtoReflect.Descriptor instead.
func (*PortAssignRequest) Descriptor() ([]byte, []int) {
	return file_contract_protobuf_port_port_proto_rawDescGZIP(), []int{1}
}

func (x *PortAssignRequest) GetPortsUsed() []string {
	if x != nil {
		return x.PortsUsed
	}
	return nil
}

func (x *PortAssignRequest) GetRequestNumberOfPort() uint32 {
	if x != nil {
		return x.RequestNumberOfPort
	}
	return 0
}

type OpenPortsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ports         []string               `protobuf:"bytes,1,rep,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenPortsRequest) Reset() {
	*x = OpenPortsRequest{}
	mi := &file_contract_protobuf_port_port_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenPortsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenPortsRequest) ProtoMessage() {}

func (x *OpenPortsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_protobuf_port_port_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenPortsRequest.ProtoReflect.Descriptor instead.
func (*OpenPortsRequest) Descriptor() ([]byte, []int) {
	return file_contract_protobuf_port_port_proto_rawDescGZIP(), []int{2}
}

func (x *OpenPortsRequest) GetPorts() []string {
	if x != nil {
		return x.Ports
	}
	return nil
}

type OpenPortsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ports         []string               `protobuf:"bytes,1,rep,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenPortsResponse) Reset() {
	*x = OpenPortsResponse{}
	mi := &file_contract_protobuf_port_port_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenPortsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenPortsResponse) ProtoMessage() {}

func (x *OpenPortsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_protobuf_port_port_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenPortsResponse.ProtoReflect.Descriptor instead.
func (*OpenPortsResponse) Descriptor() ([]byte, []int) {
	return file_contract_protobuf_port_port_proto_rawDescGZIP(), []int{3}
}

func (x *OpenPortsResponse) GetPorts() []string {
	if x != nil {
		return x.Ports
	}
	return nil
}

var File_contract_protobuf_port_port_proto protoreflect.FileDescriptor

const file_contract_protobuf_port_port_proto_rawDesc = "" +
	"\n" +
	"!contract/protobuf/port/port.proto\x12\x04port\"*\n" +
	"\x12PortAssignResponse\x12\x14\n" +
	"\x05ports\x18\x01 \x03(\tR\x05ports\"c\n" +
	"\x11PortAssignRequest\x12\x1c\n" +
	"\tportsUsed\x18\x01 \x03(\tR\tportsUsed\x120\n" +
	"\x13requestNumberOfPort\x18\x02 \x01(\rR\x13requestNumberOfPort\"(\n" +
	"\x10OpenPortsRequest\x12\x14\n" +
	"\x05ports\x18\x01 \x03(\tR\x05ports\")\n" +
	"\x11OpenPortsResponse\x12\x14\n" +
	"\x05ports\x18\x01 \x03(\tR\x05ports2\x8c\x01\n" +
	"\x04Port\x12F\n" +
	"\x11GetAvailablePorts\x12\x17.port.PortAssignRequest\x1a\x18.port.PortAssignResponse\x12<\n" +
	"\tOpenPorts\x12\x16.port.OpenPortsRequest\x1a\x17.port.OpenPortsResponseB\x16Z\x14contract/gogrpc/portb\x06proto3"

var (
	file_contract_protobuf_port_port_proto_rawDescOnce sync.Once
	file_contract_protobuf_port_port_proto_rawDescData []byte
)

func file_contract_protobuf_port_port_proto_rawDescGZIP() []byte {
	file_contract_protobuf_port_port_proto_rawDescOnce.Do(func() {
		file_contract_protobuf_port_port_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contract_protobuf_port_port_proto_rawDesc), len(file_contract_protobuf_port_port_proto_rawDesc)))
	})
	return file_contract_protobuf_port_port_proto_rawDescData
}

var file_contract_protobuf_port_port_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_contract_protobuf_port_port_proto_goTypes = []any{
	(*PortAssignResponse)(nil), // 0: port.PortAssignResponse
	(*PortAssignRequest)(nil),  // 1: port.PortAssignRequest
	(*OpenPortsRequest)(nil),   // 2: port.OpenPortsRequest
	(*OpenPortsResponse)(nil),  // 3: port.OpenPortsResponse
}
var file_contract_protobuf_port_port_proto_depIdxs = []int32{
	1, // 0: port.Port.GetAvailablePorts:input_type -> port.PortAssignRequest
	2, // 1: port.Port.OpenPorts:input_type -> port.OpenPortsRequest
	0, // 2: port.Port.GetAvailablePorts:output_type -> port.PortAssignResponse
	3, // 3: port.Port.OpenPorts:output_type -> port.OpenPortsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_contract_protobuf_port_port_proto_init() }
func file_contract_protobuf_port_port_proto_init() {
	if File_contract_protobuf_port_port_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contract_protobuf_port_port_proto_rawDesc), len(file_contract_protobuf_port_port_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contract_protobuf_port_port_proto_goTypes,
		DependencyIndexes: file_contract_protobuf_port_port_proto_depIdxs,
		MessageInfos:      file_contract_protobuf_port_port_proto_msgTypes,
	}.Build()
	File_contract_protobuf_port_port_proto = out.File
	file_contract_protobuf_port_port_proto_goTypes = nil
	file_contract_protobuf_port_port_proto_depIdxs = nil
}
