// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: contract/protobuf/metric/metric.proto

package metric

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Rank          uint32                 `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricResponse) Reset() {
	*x = MetricResponse{}
	mi := &file_contract_protobuf_metric_metric_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricResponse) ProtoMessage() {}

func (x *MetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_protobuf_metric_metric_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricResponse.ProtoReflect.Descriptor instead.
func (*MetricResponse) Descriptor() ([]byte, []int) {
	return file_contract_protobuf_metric_metric_proto_rawDescGZIP(), []int{0}
}

func (x *MetricResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MetricResponse) GetRank() uint32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type MetricRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricRequest) Reset() {
	*x = MetricRequest{}
	mi := &file_contract_protobuf_metric_metric_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricRequest) ProtoMessage() {}

func (x *MetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_protobuf_metric_metric_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricRequest.ProtoReflect.Descriptor instead.
func (*MetricRequest) Descriptor() ([]byte, []int) {
	return file_contract_protobuf_metric_metric_proto_rawDescGZIP(), []int{1}
}

var File_contract_protobuf_metric_metric_proto protoreflect.FileDescriptor

const file_contract_protobuf_metric_metric_proto_rawDesc = "" +
	"\n" +
	"%contract/protobuf/metric/metric.proto\x12\x06metric\"<\n" +
	"\x0eMetricResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x12\n" +
	"\x04rank\x18\x02 \x01(\rR\x04rank\"\x0f\n" +
	"\rMetricRequest2D\n" +
	"\x06Metric\x12:\n" +
	"\tGetMetric\x12\x15.metric.MetricRequest\x1a\x16.metric.MetricResponseB\x18Z\x16contract/gogrpc/metricb\x06proto3"

var (
	file_contract_protobuf_metric_metric_proto_rawDescOnce sync.Once
	file_contract_protobuf_metric_metric_proto_rawDescData []byte
)

func file_contract_protobuf_metric_metric_proto_rawDescGZIP() []byte {
	file_contract_protobuf_metric_metric_proto_rawDescOnce.Do(func() {
		file_contract_protobuf_metric_metric_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contract_protobuf_metric_metric_proto_rawDesc), len(file_contract_protobuf_metric_metric_proto_rawDesc)))
	})
	return file_contract_protobuf_metric_metric_proto_rawDescData
}

var file_contract_protobuf_metric_metric_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_contract_protobuf_metric_metric_proto_goTypes = []any{
	(*MetricResponse)(nil), // 0: metric.MetricResponse
	(*MetricRequest)(nil),  // 1: metric.MetricRequest
}
var file_contract_protobuf_metric_metric_proto_depIdxs = []int32{
	1, // 0: metric.Metric.GetMetric:input_type -> metric.MetricRequest
	0, // 1: metric.Metric.GetMetric:output_type -> metric.MetricResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_contract_protobuf_metric_metric_proto_init() }
func file_contract_protobuf_metric_metric_proto_init() {
	if File_contract_protobuf_metric_metric_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contract_protobuf_metric_metric_proto_rawDesc), len(file_contract_protobuf_metric_metric_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contract_protobuf_metric_metric_proto_goTypes,
		DependencyIndexes: file_contract_protobuf_metric_metric_proto_depIdxs,
		MessageInfos:      file_contract_protobuf_metric_metric_proto_msgTypes,
	}.Build()
	File_contract_protobuf_metric_metric_proto = out.File
	file_contract_protobuf_metric_metric_proto_goTypes = nil
	file_contract_protobuf_metric_metric_proto_depIdxs = nil
}
